<?php
// Hook Menu
function wysiwyg_imageupload_browser_menu() {
  $items = array();
  $items['ajax/wysiwyg_imageupload_browser'] = array(
  	'page callback' => 'wysiwyg_imageupload_browser_browser',
  	'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiyg image upload'),
  	'type' => MENU_CALLBACK,
  );
  return $items;
}
//hook form alter
function wysiwyg_imageupload_browser_form_alter(&$form, $form_state, $form_id){
  if ($form_id == 'wysiwyg_imageupload_upload_form') {
    $form['browse'] = array(
      '#value' => t('<a href="index.php?q=ajax/wysiwyg_imageupload_browser">Browse</a>'),
      '#weight' => 0,
    );
  }  
}
//generate the browser
function wysiwyg_imageupload_browser_browser(){
  global $user;
  global $base_url;
  $uid = $user->uid;
  $result = db_query('Select fid, uid, filepath from {files} where uid = %d',$uid);
  while($row = db_fetch_array($result)){//now this is some dirty code, but the good thing is we need no js at all
    print '<a href="'.$base_url.'/index.php?q=ajax/wysiwyg_imgupl/update/Title/&imagepath='.$row['filepath'].'"><img src="'.$base_url.'/'.$row['filepath'].'" width="400px" alt="'.$cid.'" /></a>';
  }   
}
