<?php
/*
 * Implementation of hook_menu
 */
function wysiwyg_imageupload_browser_menu() {
  $items = array();
  $items['ajax/wysiwyg_imageupload_browser'] = array(
  	'page callback' => 'wysiwyg_imageupload_browser_browser',
  	'page arguments' => array(3),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiyg image upload'),
  	'type' => MENU_CALLBACK,
  );
  return $items;
}
/*
 * Implementation of hook_form_alter
 */
function wysiwyg_imageupload_browser_form_alter(&$form, $form_state, $form_id){
  if ($form_id == 'wysiwyg_imageupload_upload_form') {
    $form['browse'] = array(
      '#value' => l('Browser', 'ajax/wysiwyg_imageupload_browser'),
      '#weight' => 0,
    );
  }  
}
/*
 * Generate the Browser
 */
function wysiwyg_imageupload_browser_browser(){
  jquery_ui_dialog_child_js();
  global $user;
  global $base_url;
  $uid = $user->uid;
  $result = db_query('Select fid, uid, filepath from {files} where uid = %d',$uid);
  while($row = db_fetch_array($result)){
    $output .= l('<img src="'.$base_url.'/'.$row['filepath'].'" width="400px" alt="'.$cid.'" />', 'ajax/wysiwyg_imgupl/update/Title/', array('html' => 'true', 'absolute' => TRUE, 'query' => array('imagepath' => $row['filepath'])));
  }   
  return $output;
}
