<?php
/*
 * Implementation of hook_imagecache_default_presets
 */
function wysiwyg_imageupload_browser_imagecache_default_presets() {
  $presets = array();
  $presets['wysiwyg_imageupload_browser'] = array (
    'presetname' => 'wysiwyg_imageupload_browser',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => array (
          'width' => '200',
          'height' => '200',
          'upscale' => 0,
        ),
    ),
  ));
  return $presets;
}

/*
 * Implementation of hook_menu
 */
function wysiwyg_imageupload_browser_menu() {
  $items = array();
  $items['ajax/wysiwyg_imageupload_browser/%'] = array(
    'page callback' => 'wysiwyg_imageupload_browser_browser',
    'page arguments' => array(2),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiyg image upload'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/*
 * Implementation of hook_form_alter
 */
function wysiwyg_imageupload_browser_form_alter(&$form, $form_state, $form_id){
  if ($form_id == 'wysiwyg_imageupload_upload_form') {
    $tabs = array();
    $tabs[] = '<a href="#">New Image</a>';
    $tabs[] = l(t('Browser'), 'ajax/wysiwyg_imageupload_browser/'.$form["#parameters"][2], array('title' => t('Choose a new image out of all your already uploaded ones')));
    $form['browse'] = array(
      '#value' => wysiwyg_imageupload_browser_tabs($tabs,0),
      '#weight' => 0,
    );
  }
  if ($form_id == 'wysiwyg_imageupload_admin_settings') {
    $form['wysiwyg_imageupload_browser_itemcount'] = array(
      '#type' => 'textfield',
      '#title' => t('Max. Items Displayed'),
      '#description' => t('Define how many Images should be displayed inside the Browser'),
      '#default_value' => variable_get('wysiwyg_imageupload_browser_itemcount', ''),
      '#weight' => 0,
    );
  }
}
/*
 * Generate the Browser
 */
function wysiwyg_imageupload_browser_browser($form_id){
  global $user, $base_url;
  jquery_ui_dialog_child_js();
  module_invoke('admin_menu', 'suppress');

  // Adding tabs.
  $tabs = array();
  $tabs[] = l(t('New Image'), 'ajax/wysiwyg_imgupl/add/'.arg(2), array('title' => t('Go back to the upload form and upload a new image')));
  $tabs[] = '<a href="#">'.t('Browser').'</a>';
  $output .= wysiwyg_imageupload_browser_tabs($tabs,1);

  $result = db_query('Select fid, filepath from {files} where uid = %d LIMIT %d',$user->uid, variable_get('wysiwyg_imageupload_browser_itemcount', 6));
  $output .= '<div id="wysiwyg_imageupload_browser_group" class="clearfix">';
  while($row = db_fetch_array($result)){
    $imageHTML = '<div class="browser_image">';
    $imageHTML .= theme('imagecache', 'wysiwyg_imageupload_browser', $row['filepath'], t('Insert this image'));
    $imageHTML .= '</div>';
    $output .= l($imageHTML, 'ajax/wysiwyg_imgupl/update/Title/', array(
      'title' => t('Insert this image'),
      'html' => 'true',
      'absolute' => TRUE,
      'query' => array(
        'imagepath' => $row['filepath'])
      )
    );
  }
  $output .= '</div>';

  return $output;
}
function wysiwyg_imageupload_browser_tabs($tabs,$active){
  $m = drupal_get_path('module', 'wysiwyg_imageupload_browser');
  drupal_add_css($m.'/wysiwyg_imageupload_browser.css');

  $output .= '<ul class="wysiwyg_imageupload_tabs">';
  foreach($tabs as $index => $tab){
    if($index == $active){$class = 'active';}else{$class = 'inactive';}
    $output .= '<li class="wysiwyg_imageupload_tab wysiwyg_imageupload_tab_'.$class.'">'.$tab.'</li>';
  }
  $output .= '</ul>';
  return $output;
}